# Generated by Django 4.2.30 on 2026-05-25 00:30

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('user', 'Colaborador')], default='user', max_length=20)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('num_letra', models.CharField(blank=True, help_text='Número en texto', max_length=200)),
                ('colonia', models.CharField(blank=True, max_length=200)),
                ('cp', models.CharField(blank=True, max_length=10)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('dia_pago', models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado')], max_length=20)),
                ('link_location', models.URLField(blank=True, help_text='Link de Google Maps')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('n_socio', models.CharField(blank=True, help_text='Número de socio', max_length=50)),
                ('tipo_contrato', models.CharField(choices=[('laboral', 'Laboral')], default='laboral', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('saldo_vacaciones', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('baja', 'Baja')], default='activo', max_length=20)),
                ('rfc', models.CharField(blank=True, max_length=20)),
                ('curp', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('num_ext', models.CharField(blank=True, max_length=20)),
                ('num_int', models.CharField(blank=True, max_length=20)),
                ('num_text', models.CharField(blank=True, help_text='Número en texto', max_length=200)),
                ('colonia', models.CharField(blank=True, max_length=200)),
                ('cp', models.CharField(blank=True, max_length=10)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('dia_pago', models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado')], max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_relation', models.CharField(blank=True, choices=[('familiar', 'Familiar'), ('amigo', 'Amigo'), ('vecino', 'Vecino'), ('otro', 'Otro')], max_length=50)),
                ('ref1_nombre', models.CharField(blank=True, max_length=200)),
                ('ref1_tipo', models.CharField(blank=True, max_length=50)),
                ('ref1_tiempo', models.CharField(blank=True, max_length=50)),
                ('ref1_telefono', models.CharField(blank=True, max_length=20)),
                ('ref2_nombre', models.CharField(blank=True, max_length=200)),
                ('ref2_tipo', models.CharField(blank=True, max_length=50)),
                ('ref2_tiempo', models.CharField(blank=True, max_length=50)),
                ('ref2_telefono', models.CharField(blank=True, max_length=20)),
                ('ref3_nombre', models.CharField(blank=True, max_length=200)),
                ('ref3_tipo', models.CharField(blank=True, max_length=50)),
                ('ref3_tiempo', models.CharField(blank=True, max_length=50)),
                ('ref3_telefono', models.CharField(blank=True, max_length=20)),
                ('ine_front_ref', models.CharField(blank=True, help_text='Referencia archivo INE frente', max_length=500)),
                ('ine_back_ref', models.CharField(blank=True, help_text='Referencia archivo INE reverso', max_length=500)),
                ('consentimiento_ref', models.CharField(blank=True, help_text='Referencia archivo consentimiento', max_length=500)),
                ('skill_level', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='basic', help_text='1-5 estrellas', max_length=20)),
                ('service', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('teamwork', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('feedback', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('selfhelp', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('behavior', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('time_attendance', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('availability', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('fecha_registro', models.TextField(blank=True, help_text='Fecha de registro en sistema')),
                ('baja_motivo', models.TextField(blank=True, help_text='Motivo de baja detallado')),
                ('baja_motivo_selector', models.CharField(blank=True, help_text='Motivo genérico de baja', max_length=100)),
                ('fecha_baja', models.DateField(blank=True, help_text='Fecha de baja del empleado', null=True)),
                ('recontratable', models.BooleanField(default=True, help_text='¿Puede ser recontratado?')),
                ('end_term', models.BooleanField(default=False, help_text='Terminación voluntaria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.branch')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación')], max_length=20)),
                ('field_changed', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'db_table': 'audits',
            },
        ),
    ]
